#! /usr/bin/env python3
import os
import requests
import json
dict = {}
keydict = {"title","name","date","feedback"}
for file in os.listdir("/data/feedback"):
         with open("/data/feedback/"+file,"r") as f:
              lisf = f.readlines()
              lisf = [x.strip() for x in lisf]
              dict['title'] = lisf[0]
              dict['name'] = lisf[1]
              dict['date'] = lisf[2]
              dict['feedback'] = lisf[3]
              print(requests.post(url,json = dict).status_code)
